export type ResourceTopic = "nature" | "management" | "planning" | "exam" | "general";

export type ResourceItem = {
  id: string;
  title: string;
  topic: ResourceTopic;
  topicLabel: string;
  filename: string;
  kind: "docx" | "pdf" | "xlsx";
  href?: string;
};

export const resourceCatalog: ResourceItem[] = [
  {
    id: "1-1-1-2--1-2-functions-of-business-table",
    title: "1.2 Functions of Business table",
    topic: "nature",
    topicLabel: "Nature of Business",
    filename: "1.1.1.2. 1.2 Functions of Business table.docx",
    kind: "docx",
  },
  {
    id: "1-1-1-3--2-1-legal-structures-info-sheet",
    title: "2.1 Legal Structures info sheet",
    topic: "nature",
    topicLabel: "Nature of Business",
    filename: "1.1.1.3. 2.1 Legal Structures info sheet.docx",
    kind: "docx",
  },
  {
    id: "1-1-2-2--1-2-starbucks-gears-up-for-a-comeback",
    title: "1.2 Starbucks gears up for a comeback",
    topic: "nature",
    topicLabel: "Nature of Business",
    filename: "1.1.2.2. 1.2 Starbucks gears up for a comeback.docx",
    kind: "docx",
  },
  {
    id: "1-1-3-3--1-2-pest-analysis-worksheet",
    title: "1.2 PEST ANALYSIS worksheet",
    topic: "nature",
    topicLabel: "Nature of Business",
    filename: "1.1.3.3. 1.2 PEST ANALYSIS worksheet.docx",
    kind: "docx",
  },
  {
    id: "1-1-3-4--1-3-social-influence-article---alcohol-industry",
    title: "1.3 Social Influence Article - Alcohol Industry",
    topic: "nature",
    topicLabel: "Nature of Business",
    filename: "1.1.3.4. 1.3 Social Influence Article - Alcohol Industry.pdf",
    kind: "pdf",
    href: "/downloads/social-influence-alcohol-industry.pdf",
  },
  {
    id: "1-1-3-5--1-4-smes-and-cryptocurrency",
    title: "1.4 SMEs and Cryptocurrency",
    topic: "nature",
    topicLabel: "Nature of Business",
    filename: "1.1.3.5. 1.4 SMEs and Cryptocurrency.docx",
    kind: "docx",
  },
  {
    id: "1-1-3-6--1-5-worksheet-competitive-situation-and-market-concentrations",
    title: "1.5 worksheet Competitive Situation and Market Concentrations",
    topic: "nature",
    topicLabel: "Nature of Business",
    filename: "1.1.3.6. 1.5 worksheet Competitive Situation and Market Concentrations.docx",
    kind: "docx",
  },
  {
    id: "1-1-3-7--1-6-business-stakeholders-worksheet",
    title: "1.6 Business Stakeholders worksheet",
    topic: "nature",
    topicLabel: "Nature of Business",
    filename: "1.1.3.7. 1.6 Business Stakeholders worksheet.docx",
    kind: "docx",
  },
  {
    id: "1-1-4-3--1-1-summary-of-challenges-and-strategeis-for-each-stage",
    title: "1.1 Summary of challenges and strategeis for each stage",
    topic: "nature",
    topicLabel: "Nature of Business",
    filename: "1.1.4.3. 1.1 Summary of challenges and strategeis for each stage.pdf",
    kind: "pdf",
    href: "/downloads/business-lifecycle-challenges.pdf",
  },
  {
    id: "1-1-4-4--1-2-table-the-business-lifecycle",
    title: "1.2 Table The Business Lifecycle",
    topic: "nature",
    topicLabel: "Nature of Business",
    filename: "1.1.4.4. 1.2 Table The Business Lifecycle.docx",
    kind: "docx",
  },
  {
    id: "1-1-4-5--1-3-voluntary-and-involuntary-cessation",
    title: "1.3 Voluntary and Involuntary Cessation",
    topic: "nature",
    topicLabel: "Nature of Business",
    filename: "1.1.4.5. 1.3 Voluntary and Involuntary Cessation.docx",
    kind: "docx",
  },
  {
    id: "1-1-4-6--1-4-blc-poster-activity",
    title: "1.4 BLC Poster activity",
    topic: "nature",
    topicLabel: "Nature of Business",
    filename: "1.1.4.6. 1.4 BLC Poster activity.docx",
    kind: "docx",
  },
  {
    id: "1-2-1-1--1-1-air-bnb-case-study-answers",
    title: "1.1 Air BnB Case Study answers",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.1.1. 1.1 Air BnB Case Study answers.docx",
    kind: "docx",
  },
  {
    id: "1-2-1-2--1-1-air-bnb-case-study",
    title: "1.1 Air BnB Case Study",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.1.2. 1.1 Air BnB Case Study.docx",
    kind: "docx",
  },
  {
    id: "1-2-1-4--1-2-responding-to-internal-and-external-influences",
    title: "1.2 Responding To Internal and External Influences",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.1.4. 1.2 Responding To Internal and External Influences.docx",
    kind: "docx",
  },
  {
    id: "1-2-1-5--1-3-qantas-and-virgins-strategic-alliance",
    title: "1.3 Qantas and Virgins strategic alliance",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.1.5. 1.3 Qantas and Virgins strategic alliance.docx",
    kind: "docx",
  },
  {
    id: "1-2-1-6--1-3-qantas-and-woolies-give-loyalty-partnership-a-points-boost",
    title: "1.3 Qantas and Woolies give loyalty partnership a points boost",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.1.6. 1.3 Qantas and Woolies give loyalty partnership a points boost.docx",
    kind: "docx",
  },
  {
    id: "1-2-1-7--1-4-research-activity",
    title: "1.4 Research Activity",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.1.7. 1.4 Research Activity.docx",
    kind: "docx",
  },
  {
    id: "1-2-2-1--1-1-management-approaches-booklet",
    title: "1.1 Management Approaches Booklet",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.2.1. 1.1 Management Approaches Booklet.docx",
    kind: "docx",
  },
  {
    id: "1-2-2-3--1-2-clickview-management-styles-explained-doc",
    title: "1.2 Clickview Management Styles Explained.doc",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.2.3. 1.2 Clickview Management Styles Explained.doc.docx",
    kind: "docx",
  },
  {
    id: "1-2-2-4--1-2-management-approaches-research-task",
    title: "1.2 Management Approaches Research Task",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.2.4. 1.2 Management Approaches Research Task.docx",
    kind: "docx",
  },
  {
    id: "1-2-2-5--1-2-suggested-answers-to-clickview-video",
    title: "1.2 Suggested Answers To Clickview Video",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.2.5. 1.2 Suggested Answers To Clickview Video.docx",
    kind: "docx",
  },
  {
    id: "1-2-2-6--1-2-teacher-notes-clickview-doc",
    title: "1.2 Teacher Notes Clickview.doc",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.2.6. 1.2 Teacher Notes Clickview.doc.docx",
    kind: "docx",
  },
  {
    id: "1-2-2-7--1-3-elon-musks-hardcore-management-style_-a-case-study-in-what-not-to-d",
    title: "1.3 Elon Musk's 'hardcore' management style_ a case study in what not to do",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.2.7. 1.3 Elon Musk's 'hardcore' management style_ a case study in what not to do.pdf",
    kind: "pdf",
    href: "/downloads/elon-musk-management-case-study.pdf",
  },
  {
    id: "1-2-2-8--1-3-summary-of-management-theories-and-leadership-styles",
    title: "1.3 SUMMARY OF MANAGEMENT THEORIES and leadership styles",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.2.8. 1.3 SUMMARY OF MANAGEMENT THEORIES and leadership styles.docx",
    kind: "docx",
  },
  {
    id: "1-2-3-1-1-1--1-1-a-businesss-financial-position",
    title: "1.1 A Business's Financial Position",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.3.1.1.1. 1.1 A Business's Financial Position.docx",
    kind: "docx",
  },
  {
    id: "1-2-3-1-1-10--1-2-financial-equation-summary",
    title: "1.2 Financial Equation Summary",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.3.1.1.10. 1.2 Financial Equation Summary.docx",
    kind: "docx",
  },
  {
    id: "1-2-3-1-1-2--1-1-debt-and-equity-finance-worksheet",
    title: "1.1 Debt and Equity Finance Worksheet",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.3.1.1.2. 1.1 Debt and Equity Finance Worksheet.docx",
    kind: "docx",
  },
  {
    id: "1-2-3-1-1-4--1-1-preparing-an-income-statement",
    title: "1.1 Preparing an Income Statement",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.3.1.1.4. 1.1 Preparing an Income Statement.docx",
    kind: "docx",
  },
  {
    id: "1-2-3-1-1-5--1-1-the-accounting-equation-explained",
    title: "1.1 The Accounting Equation Explained",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.3.1.1.5. 1.1 The Accounting Equation Explained.docx",
    kind: "docx",
  },
  {
    id: "1-2-3-1-1-6--1-1-understanding-the-cash-flow-statement",
    title: "1.1 Understanding The Cash Flow Statement",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.3.1.1.6. 1.1 Understanding The Cash Flow Statement.docx",
    kind: "docx",
  },
  {
    id: "1-2-3-1-1-7--1-2--financial-statements-quiz-doc",
    title: "1.2  Financial Statements Quiz.doc",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.3.1.1.7. 1.2  Financial Statements Quiz.doc.docx",
    kind: "docx",
  },
  {
    id: "1-2-3-1-1-8--1-2-breakeven-analysis-excel-example",
    title: "1.2 Breakeven analysis Excel Example",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.3.1.1.8. 1.2 Breakeven analysis Excel Example.xlsx",
    kind: "xlsx",
  },
  {
    id: "1-2-3-2-2--1-1-picture-summary-human-resource-management",
    title: "1.1 Picture Summary Human Resource Management",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.3.2.2. 1.1 Picture Summary Human Resource Management.docx",
    kind: "docx",
  },
  {
    id: "1-2-3-2-3--1-1-vocabulary-list",
    title: "1.1 Vocabulary List",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.3.2.3. 1.1 Vocabulary List.docx",
    kind: "docx",
  },
  {
    id: "1-2-3-2-4--1-2-unfair-dismissal-case-studies",
    title: "1.2 Unfair Dismissal Case Studies",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.3.2.4. 1.2 Unfair Dismissal Case Studies.docx",
    kind: "docx",
  },
  {
    id: "1-2-3-2-5--1-3-dead-white-mans-clothing",
    title: "1.3 Dead White Mans Clothing",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.3.2.5. 1.3 Dead White Mans Clothing.docx",
    kind: "docx",
  },
  {
    id: "1-2-3-3-2--1-1-intro-and-operations-booklet",
    title: "1.1 Intro and Operations BOOKLET",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.3.3.2. 1.1 Intro and Operations BOOKLET.docx",
    kind: "docx",
  },
  {
    id: "1-2-3-3-3--1-2-picture-summary-coordinating-functions-operations-doc",
    title: "1.2 Picture summary Coordinating functions Operations.DOC",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.3.3.3. 1.2 Picture summary Coordinating functions Operations.DOC.docx",
    kind: "docx",
  },
  {
    id: "1-2-3-4-2--1-2-marketing-booklet",
    title: "1.2 marketing booklet",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.3.4.2. 1.2 marketing booklet.docx",
    kind: "docx",
  },
  {
    id: "1-2-3-4-3--1-3-marketing-picture-summary",
    title: "1.3 Marketing Picture summary",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.3.4.3. 1.3 Marketing Picture summary.docx",
    kind: "docx",
  },
  {
    id: "1-2-3-4-4--1-4-marketing-product-analysis-and-taste-test",
    title: "1.4 Marketing Product Analysis and Taste Test",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.3.4.4. 1.4 Marketing Product Analysis and Taste Test.docx",
    kind: "docx",
  },
  {
    id: "1-2-3-4-5--1-5-shark-tank-marketing",
    title: "1.5 shark tank marketing",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.3.4.5. 1.5 shark tank marketing.docx",
    kind: "docx",
  },
  {
    id: "1-2-3-4-6--1-6-the-4ps-of-marketing-template",
    title: "1.6 The 4Ps of Marketing template",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.3.4.6. 1.6 The 4Ps of Marketing template.docx",
    kind: "docx",
  },
  {
    id: "1-2-4-2--1-1-applying-polc-through-a-study-timetable",
    title: "1.1 Applying POLC through a study timetable",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.4.2. 1.1 Applying POLC through a study timetable.docx",
    kind: "docx",
  },
  {
    id: "1-2-4-3--1-1-booklet-nature-of-management",
    title: "1.1 booklet nature of management",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.4.3. 1.1 booklet nature of management.docx",
    kind: "docx",
  },
  {
    id: "1-2-4-4--1-1-vea-polc-video-questions-doc",
    title: "1.1 VEA POLC video questions.doc",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.4.4. 1.1 VEA POLC video questions.doc.docx",
    kind: "docx",
  },
  {
    id: "1-2-4-5--1-2-2020-mcdonalds-letter-from-ceo-to-shareholders",
    title: "1.2 2020 MCDonalds Letter From CEO to Shareholders",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.4.5. 1.2 2020 MCDonalds Letter From CEO to Shareholders.pdf",
    kind: "pdf",
    href: "/downloads/mcdonalds-ceo-letter-2020.pdf",
  },
  {
    id: "1-2-4-6--1-2-management-skills",
    title: "1.2 Management Skills",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.4.6. 1.2 Management Skills.docx",
    kind: "docx",
  },
  {
    id: "1-2-4-7--1-2-staff-involvement-notes",
    title: "1.2 Staff Involvement Notes",
    topic: "management",
    topicLabel: "Business Management",
    filename: "1.2.4.7. 1.2 Staff Involvement Notes.docx",
    kind: "docx",
  },
  {
    id: "1-3-1-2--1-2-economic-contributions-of-smes",
    title: "1.2 Economic Contributions of SMEs",
    topic: "planning",
    topicLabel: "Business Planning",
    filename: "1.3.1.2. 1.2 Economic Contributions of SMEs.docx",
    kind: "docx",
  },
  {
    id: "1-3-1-5--1-3-case-study-mr-yum\u2019s-$100m-global-expansion-plans-revealed",
    title: "1.3 Case Study Mr Yum\u2019s $100m global expansion plans revealed",
    topic: "planning",
    topicLabel: "Business Planning",
    filename: "1.3.1.5. 1.3 Case Study Mr Yum\u2019s $100m global expansion plans revealed.pdf",
    kind: "pdf",
  },
  {
    id: "1-3-2-1--1-1-key-influences-in-establishing-a-sme-booklet",
    title: "1.1 Key Influences in Establishing a SME Booklet",
    topic: "planning",
    topicLabel: "Business Planning",
    filename: "1.3.2.1. 1.1 Key Influences in Establishing a SME Booklet.docx",
    kind: "docx",
  },
  {
    id: "1-3-2-2--1-1-key-influences-in-establishing-a-sme-booklet",
    title: "1.1 Key Influences in Establishing a SME Booklet",
    topic: "planning",
    topicLabel: "Business Planning",
    filename: "1.3.2.2. 1.1 Key Influences in Establishing a SME Booklet.pdf",
    kind: "pdf",
  },
  {
    id: "1-3-2-4--1-2-site-study-qvb",
    title: "1.2 Site Study QVB",
    topic: "planning",
    topicLabel: "Business Planning",
    filename: "1.3.2.4. 1.2 Site Study QVB.docx",
    kind: "docx",
  },
  {
    id: "1-3-2-5--1-3-revision-sheet_past-papers-short-answer_er-questions",
    title: "1.3 Revision Sheet_Past Papers Short Answer_ER Questions",
    topic: "planning",
    topicLabel: "Business Planning",
    filename: "1.3.2.5. 1.3 Revision Sheet_Past Papers Short Answer_ER Questions.docx",
    kind: "docx",
  },
  {
    id: "1-3-3-2--1-1-sme-business-plan-structure",
    title: "1.1 SME Business Plan Structure",
    topic: "planning",
    topicLabel: "Business Planning",
    filename: "1.3.3.2. 1.1 SME Business Plan Structure.docx",
    kind: "docx",
  },
  {
    id: "1-3-3-3--1-2-business-goals-handout",
    title: "1.2 Business Goals Handout",
    topic: "planning",
    topicLabel: "Business Planning",
    filename: "1.3.3.3. 1.2 Business Goals Handout.docx",
    kind: "docx",
  },
  {
    id: "1-3-3-4--1-3-notes-on-the-business-planning-process",
    title: "1.3 Notes on the business planning process",
    topic: "planning",
    topicLabel: "Business Planning",
    filename: "1.3.3.4. 1.3 Notes on the business planning process.docx",
    kind: "docx",
  },
  {
    id: "1-3-4-3--1-2-business-case-study-comprehension-f45",
    title: "1.2 Business Case Study Comprehension F45",
    topic: "planning",
    topicLabel: "Business Planning",
    filename: "1.3.4.3. 1.2 Business Case Study Comprehension F45.docx",
    kind: "docx",
  },
  {
    id: "1-3-4-4--1-2-case-study-f45_from-cult-to-chaos",
    title: "1.2 Case Study F45_From Cult to Chaos",
    topic: "planning",
    topicLabel: "Business Planning",
    filename: "1.3.4.4. 1.2 Case Study F45_From Cult to Chaos.docx",
    kind: "docx",
  },
  {
    id: "1-3-5--topic-3-business-planning-syllabus-mapping-document",
    title: "Topic 3 Business Planning Syllabus Mapping Document",
    topic: "planning",
    topicLabel: "Business Planning",
    filename: "1.3.5. Topic 3 Business Planning Syllabus Mapping Document.docx",
    kind: "docx",
  },
  {
    id: "exam-preparation-slides",
    title: "Preliminary Exam Preparation Slides",
    topic: "exam",
    topicLabel: "Exam Preparation",
    filename: "1.4.2. 1.1 Prelin Exam Preparation.pptx - Google Slides.pdf",
    kind: "pdf",
  },
];

export const downloadableResources = resourceCatalog.filter(
  (r): r is ResourceItem & { href: string } => Boolean(r.href)
);

export const resourcesByTopic = (topic: ResourceTopic) => resourceCatalog.filter((r) => r.topic === topic);
